const helpers = require('./helpers');

module.exports.pullRequestData = {
  headers: [
    'server',
    'GitHub.com',
    'date',
    'Wed, 06 May 2020 01:20:39 GMT',
    'content-type',
    'application/json; charset=utf-8',
    'status',
    '200 OK',
    'cache-control',
    'public, max-age=60, s-maxage=60',
    'vary',
    'Accept, Accept-Encoding, Accept, X-Requested-With',
    'etag',
    'W/"4eae27e8025a892b8493425d2ced16b8"',
    'x-github-media-type',
    'github.v3; format=json',
    'access-control-expose-headers',
    'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    'access-control-allow-origin',
    '*',
    'strict-transport-security',
    'max-age=31536000; includeSubdomains; preload',
    'x-frame-options',
    'deny',
    'x-content-type-options',
    'nosniff',
    'x-xss-protection',
    '1; mode=block',
    'referrer-policy',
    'origin-when-cross-origin, strict-origin-when-cross-origin',
    'content-security-policy',
    "default-src 'none'",
    'content-encoding',
    'gzip',
    'X-Ratelimit-Limit',
    '60',
    'X-Ratelimit-Remaining',
    '54',
    'X-Ratelimit-Reset',
    '1588729411',
    'Accept-Ranges',
    'bytes',
    'Transfer-Encoding',
    'chunked',
    'Connection',
    'close',
    'X-GitHub-Request-Id',
    'C204:467A:CAE8B6:15C27D3:5EB210E7'
  ],
  responses: {
    full: helpers.encode(require('./pulls.json')),
    empty: helpers.encode([])
  }
};
